REGISTRATION_MAIL_TEMPLATE = """
Hello {username},

this mail is auto generated by the bot on TUM Heilbronn Discord server.
Please send the message below in the #registration channel to register yourself as a student.

/register {register_code}

If you have any problem regarding to this registering process, please contact taiki#2104 on Discord or <taiki.okano@tum.de>.

Kind regards,
Your TUM Heilbronn Discord server maintenance team (mainly me).
"""
