name: Deploy To Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    name: Deploy To Heroku
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Secrets Variables
        working-directory: ./
        run: |
          sed -i "s/GH_SECRETS_DISCORD_TOKEN/${{secrets.DISCORD_TOKEN}}/g" secrets.py

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
